In [2]:
import sys
import numpy as np

In [3]:
#  Basic Numpy arrays

np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1, 2, 3, 4])

In [5]:
b = np.array([0, .5, 1, 1.5, 2])

In [6]:
a[0], a[1]

(1, 2)

In [10]:
a[0:]

array([1, 2, 3, 4])

In [12]:
# 3rd index element is not included 
a[1:3]

array([2, 3])

In [14]:
a[1:-1]


array([2, 3])

In [15]:
a[::2]

array([1, 3])

In [16]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [17]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [19]:
b[[0, 2, -1]]

array([0., 1., 2.])

ARRAy TYPES

In [20]:
a 

array([1, 2, 3, 4])

In [21]:
a.dtype

dtype('int32')

In [22]:
b.dtype

dtype('float64')

In [27]:
# the numpy array with specified dtype 
c = np.array([1, 2, 3, 4], dtype=int)

In [28]:
c.dtype

dtype('int32')

In [29]:
d = np.array(['a', 'b', 'c', 'd']) 

In [30]:
d.dtype

dtype('<U1')

In [31]:
e = np.array([{'a': 1}, sys])

In [32]:
e.dtype

dtype('O')

Dimensions and Shapes

In [37]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [38]:
# returns (rows, columns)
A.shape

(3, 3)

In [39]:
# returns no of dimensions 
A.ndim

2

In [40]:
A.size

9

In [41]:
B = np.array([
    [
        [12, 11, 10],
        [8, 8, 7],

    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [42]:
B

array([[[12, 11, 10],
        [ 8,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [45]:
# returns (number of matrix, rows, columns)
B.shape

(2, 2, 3)

In [46]:
B.ndim

3

In [47]:
B.size
# if the shape is not consistent. it'll just fall back 

12

In [51]:
E = np.array([
    [
        [11, 10, 9],
        [8, 7, 6],
    ],
    [
        [6, 5, 4]
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

Indexing and slicing of matrix

In [54]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
# below is for example
#     0  1  2  
# 0   1  2  3
# 1  '4'  5  6
# 2   7  8  9




In [55]:
A[1]

array([4, 5, 6])

In [59]:
A[1][0]

4

In [60]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
A[:, :2]

# first colons (:) represents columns here it is all selected 
# second para states, at columnar level every column from all to within 2 which is equivalent to :2 in this case 


array([[1, 2],
       [4, 5],
       [7, 8]])

In [62]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [67]:
A[:2, 2:]

array([[3],
       [6]])

In [68]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
 A[1] = np.array([10, 10, 10])

In [70]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [73]:
A[2] = 99
A

# here in this case numpy will automatically expand the value according to the number of dimensions we have. 

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

`SUMMARY STATISTICS`

In [74]:
a = np.array([1, 2,3, 4])
a.sum()

10

In [79]:
np.mean(a)

2.5

In [78]:
sts = np.std(a)
sts

1.118033988749895

In [80]:
a.var()

1.25

In [81]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [82]:
A.sum()

45

In [83]:
A.mean()

5.0

In [84]:
A.std()

2.581988897471611

In [85]:
A.sum(axis=0)
# axis = 0 refers to the coumn-wise addtion of elements in matrix 

array([12, 15, 18])

In [86]:
A.sum(axis=1) 
# axis = 1 refers to the row-wise addition of elements in matrix

array([ 6, 15, 24])

In [89]:
print(A.std(axis=0))
print(A.std(axis=1))

[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]


In [90]:
print(A.mean(axis=0))
print(A.mean(axis=1))

[4. 5. 6.]
[2. 5. 8.]


`BROADCASTING AND VECTORIZED OPERATIONS`